swagger: '2.0'
info:
  description: Initial API for FHDA
  version: "1.1.0"
  title: FHDA API
  # put the contact info for your development or API team

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls

paths:
  /course_by_quarter:
    get:
      tags:
      - admins
      summary: get course info
      operationId: getCourseByQuarter
      description: |
        Search for course by quarter
      produces:
      - application/json
      parameters:
      - in: query
        name: quarter
        description: the quarter for searching
        type: string

      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
        400:
          description: bad input parameter
          
  /course_by_quarter_and_dept:
    get:
      tags:
      - admins
      summary: get course info
      operationId: getCourseByQuarterAndDept
      description: |
        Search for course by inputing both quarter and department name
      produces:
      - application/json
      parameters:
      - in: query
        name: quarter
        description: the quarter for searching
        type: string
      - in: query
        name: dept
        description: the department name for searching
        type: string

      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Course'
        400:
          description: bad input parameter
          
          
          
  /add_course:
    post:
      tags:
      - admins
      summary: adds a course
      operationId: addCourse
      description: Adds a course to the system
      parameters:
      - in: body
        name: course
        description: course object to add
        schema:
          $ref: '#/definitions/Course'
      responses:
        201:
          description: course created
        400:
          description: invalid input, object invalid
        409:
          description: an existing course already exists
definitions:
  Course:
    type: object
    required:
    - crn
    - courseName
    - instructorName
    - Dates
    - Time
    properties:
      crn:
        type: string
        format: uuid
        example: 00002
      courseName:
        type: string
        example: FINAN ACCOUNTNG I
      startDate:
        type: string
        format: date
        example: 2018-09-02
      endDate:
        type: string
        format: date
        example: 2018-12-12
      startTime:
        type: string
        example: 8:00:00
      endTime:
        type: string
        example: 10:00:00
      capacity:
        type: integer
        example: 40
      wl_capacity:
        type: integer
        example: 10
      active:
        type: array
        items:
          type: integer
          format: int32
          example: [0, 0, 1, 13]
      wl_active:
        type: array
        items:
          type: integer
          format: int32
          example: [0, 0, 0, 0]
      fetchTime:
        type: array
        items:
          type: string
          format: date-time
          example: ['2018-07-02T15:00:00Z', '2018-07-02T18:00:00Z', 
                            '2018-07-03T15:00:00Z', '2018-07-03T18:00:00Z']
      instructor:
        $ref: '#/definitions/Instructor'
      department:
        $ref: '#/definitions/Department/properties/dept_name'
  Instructor:
    required:
    - name
    properties:
      name:
        type: string
        example: Farshod Mosh
      email:
        type: string
        example: moshfarshod@fhda.edu
      phone:
        type: string
        example: 1234567890
  Department:
    required:
    - dept_name
    properties:
      dept_name:
        type: string
        example: ACCT
      courses:
        type: array
        example: ['00002', '00004']
      instructors:
        type: array
        example: ['Accounting Instructor', 'Accounting Professor']
        
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /yifeili98/FHDA_Incubator/1.1.0
schemes:
 - https